CREATE TABLE `employee` (
  `EMP_ID` int(11) NOT NULL,
  `EMP_NAME` varchar(20) NOT NULL,
  `EMP_EMAIL` varchar(30) NOT NULL,
  `EMP_MOB_NO` bigint(20) NOT NULL,
  `EMP_DPT_NAME` varchar(20) DEFAULT NULL,
  `EMP_DATE_JOINED` date NOT NULL,
  `EMP_MGR_ID` int(11) DEFAULT NULL,
  `EMP_LEAVE_BALANCE` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMP_ID`),
  KEY `EMP_MGR_ID` (`EMP_MGR_ID`),
  CONSTRAINT `employee_ibfk_1` FOREIGN KEY (`EMP_MGR_ID`) REFERENCES `employee` (`EMP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `employlogin` (
  `EMP_ID` int(11) DEFAULT NULL,
  `SecretCode` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `leave_history` (
  `LEA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LEA_START_DATE` date NOT NULL,
  `LEA_END_DATE` date NOT NULL,
  `LEA_NO_OF_DAYS` int(11) DEFAULT NULL,
  `LEA_REASON` varchar(100) DEFAULT NULL,
  `LEA_TYPE` enum('EL') DEFAULT NULL,
  `LEA_APPLIED_ON` date DEFAULT NULL,
  `LEA_MGR_COMMENTS` varchar(100) DEFAULT NULL,
  `EMP_ID` int(11) DEFAULT NULL,
  `LEA_STATUS` enum('APPROVED','DENIED','PENDING') DEFAULT NULL,
  PRIMARY KEY (`LEA_ID`),
  KEY `EMP_ID` (`EMP_ID`),
  CONSTRAINT `leave_history_ibfk_1` FOREIGN KEY (`EMP_ID`) REFERENCES `employee` (`EMP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


